package pt.isec.swipe_maths

enum class ConnectionStates {
    SERVER_CONNECTING,
    SERVER_CONNECTED,
    SERVER_ERROR,
    NO_CONNECTION,
    CLIENT_CONNECTING,
    CONNECTION_ESTABLISHED,
    RETRIEVING_CLIENT_INFO,
    RETRIEVING_PLAYERS_LIST,
    WAITING_FOR_PLAYERS, CONNECTION_ERROR,
    CONNECTION_ENDED,
    START_GAME
}